// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIyIf7u2_m719LbA3yipo7lVp3bTTBZNc',
    appId: '1:565433370234:web:fcad883ceae0aa3a7f1dc3',
    messagingSenderId: '565433370234',
    projectId: 'posfirebase-96abd',
    authDomain: 'posfirebase-96abd.firebaseapp.com',
    storageBucket: 'posfirebase-96abd.firebasestorage.app',
    measurementId: 'G-F13CZEQMY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ifd7UcXG7oQpjbJ1Z2--eebOdh4P3WA',
    appId: '1:565433370234:android:025c1b5a21d4a9077f1dc3',
    messagingSenderId: '565433370234',
    projectId: 'posfirebase-96abd',
    storageBucket: 'posfirebase-96abd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqWdHQXARwvTJjFH_3az1NrWGR-nC8TjY',
    appId: '1:565433370234:ios:6724146a0ddf8e207f1dc3',
    messagingSenderId: '565433370234',
    projectId: 'posfirebase-96abd',
    storageBucket: 'posfirebase-96abd.firebasestorage.app',
    iosBundleId: 'com.example.floPrix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqWdHQXARwvTJjFH_3az1NrWGR-nC8TjY',
    appId: '1:565433370234:ios:6724146a0ddf8e207f1dc3',
    messagingSenderId: '565433370234',
    projectId: 'posfirebase-96abd',
    storageBucket: 'posfirebase-96abd.firebasestorage.app',
    iosBundleId: 'com.example.floPrix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIyIf7u2_m719LbA3yipo7lVp3bTTBZNc',
    appId: '1:565433370234:web:512f523e33e7d4bc7f1dc3',
    messagingSenderId: '565433370234',
    projectId: 'posfirebase-96abd',
    authDomain: 'posfirebase-96abd.firebaseapp.com',
    storageBucket: 'posfirebase-96abd.firebasestorage.app',
    measurementId: 'G-2FLKH3ZET3',
  );
}
